[package]
name = "realtime_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8.0"
serde = "1.0.219"
serde_json = "1.0.140"
futures = "0.3"
